name: Validate

on:
  pull_request:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  satis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Composer repository
        run: docker run --rm -v "$PWD:/build" -w /build composer/satis:latest build satis.json public
